// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRpdmIsPSFDb4NHI8cxktxzViVK4Jp3ds',
    appId: '1:906745540819:web:d43acdf2817a4e71346426',
    messagingSenderId: '906745540819',
    projectId: 'newapp-7a139',
    authDomain: 'newapp-7a139.firebaseapp.com',
    storageBucket: 'newapp-7a139.appspot.com',
    measurementId: 'G-9LZB68BQRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANTHUtyZAA-3vdjVzM114e7Z4ppAfla8I',
    appId: '1:906745540819:android:9e9afd977e7a7e1d346426',
    messagingSenderId: '906745540819',
    projectId: 'newapp-7a139',
    storageBucket: 'newapp-7a139.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOl7nc0U3aPtSvw7VVquLZF9ZU-FFUsjQ',
    appId: '1:906745540819:ios:ba0b7af74ace124e346426',
    messagingSenderId: '906745540819',
    projectId: 'newapp-7a139',
    storageBucket: 'newapp-7a139.appspot.com',
    iosBundleId: 'com.example.fullstack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOl7nc0U3aPtSvw7VVquLZF9ZU-FFUsjQ',
    appId: '1:906745540819:ios:ba0b7af74ace124e346426',
    messagingSenderId: '906745540819',
    projectId: 'newapp-7a139',
    storageBucket: 'newapp-7a139.appspot.com',
    iosBundleId: 'com.example.fullstack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRpdmIsPSFDb4NHI8cxktxzViVK4Jp3ds',
    appId: '1:906745540819:web:67c43937dc0ec888346426',
    messagingSenderId: '906745540819',
    projectId: 'newapp-7a139',
    authDomain: 'newapp-7a139.firebaseapp.com',
    storageBucket: 'newapp-7a139.appspot.com',
    measurementId: 'G-T2NTKNC074',
  );
}
