on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release Android"

jobs:
  build:
    name: Build & Release Android
    runs-on: macos-latest
    steps:
      # Check out the code from your repository
      - uses: actions/checkout@v3
        # Use Node.js 20 for compatibility
        with:
          node-version: '20'

      # Setup Flutter environment (without Java version check)
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Build the Android APK (Release)
      - run: flutter build apk --release --split-per-abi

      # Upload the APK artifacts
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
